/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthydiet;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    int totalM=0;
    int totalV=0;
    int totalD=0;
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainClassPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMeat = new javax.swing.JLabel();
        lblVegetables = new javax.swing.JLabel();
        lblDesert = new javax.swing.JLabel();
        bigPanelMeat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCheckBox1 = new javax.swing.JCheckBox();
        cbom1 = new javax.swing.JCheckBox();
        cbom2 = new javax.swing.JCheckBox();
        cbom3 = new javax.swing.JCheckBox();
        cbom4 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTotalMeat = new javax.swing.JLabel();
        bigPanelVegetables = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblTotalVegetables = new javax.swing.JLabel();
        bigPanelDesert = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cboD1 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        cboD2 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        cboD3 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblTotalDesert = new javax.swing.JLabel();
        backPanel = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        lblCalculate = new javax.swing.JLabel();
        lblReset = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setBounds(new java.awt.Rectangle(550, 50, 0, 0));
        setUndecorated(true);
        setResizable(false);

        mainClassPanel.setBackground(new java.awt.Color(255, 204, 204));
        mainClassPanel.setMinimumSize(new java.awt.Dimension(288, 401));
        mainClassPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(255, 204, 255));
        homePanel.setPreferredSize(new java.awt.Dimension(288, 401));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Healthy Diet");
        homePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 270, 67));

        lblMeat.setBackground(new java.awt.Color(102, 0, 102));
        lblMeat.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblMeat.setForeground(new java.awt.Color(51, 0, 0));
        lblMeat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMeat.setText("MEAT");
        lblMeat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblMeat.setName("lblMeat"); // NOI18N
        lblMeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMeatMouseClicked(evt);
            }
        });
        homePanel.add(lblMeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 270, 52));

        lblVegetables.setBackground(new java.awt.Color(102, 0, 102));
        lblVegetables.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblVegetables.setForeground(new java.awt.Color(51, 153, 0));
        lblVegetables.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVegetables.setText("VEGETABLES");
        lblVegetables.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblVegetables.setName("lblVegetables"); // NOI18N
        lblVegetables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVegetablesMouseClicked(evt);
            }
        });
        homePanel.add(lblVegetables, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, 270, 52));

        lblDesert.setBackground(new java.awt.Color(102, 0, 102));
        lblDesert.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblDesert.setForeground(new java.awt.Color(255, 153, 0));
        lblDesert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesert.setText("DESERT & JUICE");
        lblDesert.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblDesert.setName("lblDesert"); // NOI18N
        lblDesert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDesertMouseClicked(evt);
            }
        });
        homePanel.add(lblDesert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, 270, 52));

        mainClassPanel.add(homePanel, "card2");

        bigPanelMeat.setBackground(new java.awt.Color(255, 204, 255));
        bigPanelMeat.setMaximumSize(new java.awt.Dimension(288, 401));
        bigPanelMeat.setMinimumSize(new java.awt.Dimension(288, 401));
        bigPanelMeat.setPreferredSize(new java.awt.Dimension(288, 401));
        bigPanelMeat.setLayout(new java.awt.GridLayout(10, 2));

        jCheckBox1.setText("chicken");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jCheckBox1);

        bigPanelMeat.add(jScrollPane1);

        cbom1.setText("jCheckBox1");
        cbom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbom1ActionPerformed(evt);
            }
        });
        bigPanelMeat.add(cbom1);

        cbom2.setText("beef");
        cbom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbom2MouseClicked(evt);
            }
        });
        bigPanelMeat.add(cbom2);

        cbom3.setText("jCheckBox1");
        cbom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbom3ActionPerformed(evt);
            }
        });
        bigPanelMeat.add(cbom3);

        cbom4.setText("fish");
        cbom4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbom4MouseClicked(evt);
            }
        });
        bigPanelMeat.add(cbom4);

        jCheckBox6.setText("jCheckBox1");
        bigPanelMeat.add(jCheckBox6);

        jCheckBox7.setText("pork");
        bigPanelMeat.add(jCheckBox7);

        jCheckBox8.setText("jCheckBox1");
        bigPanelMeat.add(jCheckBox8);

        jCheckBox9.setText("jCheckBox1");
        bigPanelMeat.add(jCheckBox9);

        jCheckBox10.setText("jCheckBox1");
        bigPanelMeat.add(jCheckBox10);

        jCheckBox11.setText("jCheckBox1");
        bigPanelMeat.add(jCheckBox11);

        jCheckBox12.setText("jCheckBox1");
        bigPanelMeat.add(jCheckBox12);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total :: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bigPanelMeat.add(jPanel3);

        lblTotalMeat.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblTotalMeat.setText("jLabel4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalMeat, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalMeat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bigPanelMeat.add(jPanel4);

        mainClassPanel.add(bigPanelMeat, "card3");
        bigPanelMeat.getAccessibleContext().setAccessibleParent(mainClassPanel);

        bigPanelVegetables.setBackground(new java.awt.Color(255, 204, 255));
        bigPanelVegetables.setMaximumSize(new java.awt.Dimension(288, 401));
        bigPanelVegetables.setMinimumSize(new java.awt.Dimension(288, 401));
        bigPanelVegetables.setPreferredSize(new java.awt.Dimension(288, 401));
        bigPanelVegetables.setLayout(new java.awt.GridLayout(10, 2));

        jCheckBox13.setText("chicken");
        jScrollPane2.setViewportView(jCheckBox13);

        bigPanelVegetables.add(jScrollPane2);

        jCheckBox14.setText("jCheckBox1");
        bigPanelVegetables.add(jCheckBox14);

        jCheckBox15.setText("beef");
        bigPanelVegetables.add(jCheckBox15);

        jCheckBox16.setText("jCheckBox1");
        bigPanelVegetables.add(jCheckBox16);

        jCheckBox17.setText("fish");
        jCheckBox17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox17MouseClicked(evt);
            }
        });
        bigPanelVegetables.add(jCheckBox17);

        jCheckBox18.setText("jCheckBox1");
        bigPanelVegetables.add(jCheckBox18);

        jCheckBox19.setText("jCheckBox1");
        bigPanelVegetables.add(jCheckBox19);

        jCheckBox20.setText("jCheckBox1");
        bigPanelVegetables.add(jCheckBox20);

        jCheckBox21.setText("jCheckBox1");
        bigPanelVegetables.add(jCheckBox21);

        jCheckBox22.setText("jCheckBox1");
        bigPanelVegetables.add(jCheckBox22);

        jCheckBox23.setText("jCheckBox1");
        bigPanelVegetables.add(jCheckBox23);

        jCheckBox24.setText("jCheckBox1");
        bigPanelVegetables.add(jCheckBox24);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total :: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        bigPanelVegetables.add(jPanel5);

        lblTotalVegetables.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblTotalVegetables.setText("jLabel4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalVegetables, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalVegetables, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        bigPanelVegetables.add(jPanel6);

        mainClassPanel.add(bigPanelVegetables, "card3");

        bigPanelDesert.setBackground(new java.awt.Color(255, 204, 255));
        bigPanelDesert.setMaximumSize(new java.awt.Dimension(288, 401));
        bigPanelDesert.setMinimumSize(new java.awt.Dimension(288, 401));
        bigPanelDesert.setPreferredSize(new java.awt.Dimension(288, 401));
        bigPanelDesert.setLayout(new java.awt.GridLayout(10, 2));

        cboD1.setText("Butter Bread");
        cboD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboD1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(cboD1);

        bigPanelDesert.add(jScrollPane3);

        jCheckBox26.setText("jCheckBox1");
        bigPanelDesert.add(jCheckBox26);

        cboD2.setText("Donut");
        cboD2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboD2MouseClicked(evt);
            }
        });
        bigPanelDesert.add(cboD2);

        jCheckBox28.setText("jCheckBox1");
        bigPanelDesert.add(jCheckBox28);

        cboD3.setText("Tea");
        cboD3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboD3MouseClicked(evt);
            }
        });
        bigPanelDesert.add(cboD3);

        jCheckBox30.setText("jCheckBox1");
        bigPanelDesert.add(jCheckBox30);

        jCheckBox31.setText("jCheckBox1");
        bigPanelDesert.add(jCheckBox31);

        jCheckBox32.setText("jCheckBox1");
        bigPanelDesert.add(jCheckBox32);

        jCheckBox33.setText("jCheckBox1");
        bigPanelDesert.add(jCheckBox33);

        jCheckBox34.setText("jCheckBox1");
        bigPanelDesert.add(jCheckBox34);

        jCheckBox35.setText("jCheckBox1");
        bigPanelDesert.add(jCheckBox35);

        jCheckBox36.setText("jCheckBox1");
        bigPanelDesert.add(jCheckBox36);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Total :: ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        bigPanelDesert.add(jPanel7);

        lblTotalDesert.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblTotalDesert.setText("jLabel4");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalDesert, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalDesert, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        bigPanelDesert.add(jPanel8);

        mainClassPanel.add(bigPanelDesert, "card3");

        backPanel.setBackground(new java.awt.Color(255, 204, 255));

        lblBack.setBackground(new java.awt.Color(255, 204, 255));
        lblBack.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("BACK");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        lblCalculate.setBackground(new java.awt.Color(255, 204, 255));
        lblCalculate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCalculate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalculate.setText("CALCULATE");
        lblCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalculateMouseClicked(evt);
            }
        });

        lblReset.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReset.setText("RESET");
        lblReset.setMaximumSize(new java.awt.Dimension(35, 17));
        lblReset.setMinimumSize(new java.awt.Dimension(35, 17));
        lblReset.setPreferredSize(new java.awt.Dimension(35, 17));
        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReset, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCalculate)
                .addGap(18, 18, 18)
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lblReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblClose.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClose.setText("X ");
        lblClose.setToolTipText("Exit");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainClassPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainClassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMeatMouseClicked
        // TODO add your handling code here:
        //Meat
        homePanel.setVisible(false);
        bigPanelVegetables.setVisible(false);
        bigPanelDesert.setVisible(false);
        
        bigPanelMeat.setVisible(true);
    }//GEN-LAST:event_lblMeatMouseClicked

    private void lblVegetablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVegetablesMouseClicked
        // TODO add your handling code here:
        //vegetables
        homePanel.setVisible(false);
        bigPanelMeat.setVisible(false);
        bigPanelDesert.setVisible(false);
        
        bigPanelVegetables.setVisible(true);
    }//GEN-LAST:event_lblVegetablesMouseClicked

    private void lblDesertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDesertMouseClicked
        // TODO add your handling code here:
        //desert
        homePanel.setVisible(false);
        bigPanelMeat.setVisible(false);
        bigPanelVegetables.setVisible(false);
        
        bigPanelDesert.setVisible(true);
    }//GEN-LAST:event_lblDesertMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        bigPanelMeat.setVisible(false);
        bigPanelVegetables.setVisible(false);
        bigPanelDesert.setVisible(false);

        homePanel.setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void cbom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbom1ActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
         if(jCheckBox1.isSelected())
        {
        int chicken=300;
        totalM+=chicken;
        //System.out.print(total);
        lblTotalMeat.setText(String.valueOf(totalM)+"cal");
        }
        else
        {
        int chicken=300;
        totalM-=chicken;
        //System.out.print(total);
        lblTotalMeat.setText(String.valueOf(totalM)+"cal");
        }
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void cbom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbom2MouseClicked
        // TODO add your handling code here:
         if(cbom2.isSelected())
        {
        int beef=435;
        totalM+=beef;
        //System.out.print(total);
        lblTotalMeat.setText(String.valueOf(totalM)+"cal");
        }
        else
        {
        int beef=435;
        totalM-=beef;
        //System.out.print(total);
        lblTotalMeat.setText(String.valueOf(totalM)+"cal");
        }
    }//GEN-LAST:event_cbom2MouseClicked

    private void cboD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboD1MouseClicked
        // TODO add your handling code here:
        int butterBread=130;
         if(cboD1.isSelected())
        {
        
        totalD+=butterBread;
        //System.out.print(total);
        lblTotalDesert.setText(String.valueOf(totalD)+"cal");
        }
        else
        {
        
        totalD-=butterBread;
        //System.out.print(total);
        lblTotalDesert.setText(String.valueOf(totalD)+"cal");
        }
    }//GEN-LAST:event_cboD1MouseClicked

    private void lblCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalculateMouseClicked
        // TODO add your handling code here:
        String msg;
        int totalCalorie;
        totalCalorie=totalM+totalV+totalD;
        msg=String.valueOf(totalCalorie);
        JOptionPane.showMessageDialog(this, msg,"Calorie in your body",1);
    }//GEN-LAST:event_lblCalculateMouseClicked

    private void cboD2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboD2MouseClicked
        // TODO add your handling code here:
        int donut=250;
         if(cboD2.isSelected())
        {
        
        totalD+=donut;
        //System.out.print(total);
        lblTotalDesert.setText(String.valueOf(totalD)+"cal");
        }
        else
        {
        
        totalD-=donut;
        //System.out.print(total);
        lblTotalDesert.setText(String.valueOf(totalD)+"cal");
        }
    }//GEN-LAST:event_cboD2MouseClicked

    private void cboD3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboD3MouseClicked
        // TODO add your handling code here:
        int tea=110;
         if(cboD3.isSelected())
        {
        
        totalD+=tea;
        //System.out.print(total);
        lblTotalDesert.setText(String.valueOf(totalD)+"cal");
        }
        else
        {
        
        totalD-=tea;
        //System.out.print(total);
        lblTotalDesert.setText(String.valueOf(totalD)+"cal");
        }
    }//GEN-LAST:event_cboD3MouseClicked

    private void lblResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseClicked
        // TODO add your handling code here:
        int totalM=0;
        int totalV=0;
        int totalD=0;
        lblTotalMeat.setText("0 cal");
        lblTotalVegetables.setText("0 cal");
        lblTotalDesert.setText("0 cal");
    }//GEN-LAST:event_lblResetMouseClicked

    private void jCheckBox17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox17MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jCheckBox17MouseClicked

    private void cbom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbom3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbom3ActionPerformed

    private void cbom4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbom4MouseClicked
        // TODO add your handling code here:
        int fish=240;
        if(cbom4.isSelected())
        {
        totalM+=fish;
        //System.out.print(total);
        lblTotalMeat.setText(String.valueOf(totalM)+"cal");
        }
        else
        {
        
        totalM-=fish;
        //System.out.print(total);
        lblTotalMeat.setText(String.valueOf(totalM)+"cal");
        }
    }//GEN-LAST:event_cbom4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JPanel bigPanelDesert;
    private javax.swing.JPanel bigPanelMeat;
    private javax.swing.JPanel bigPanelVegetables;
    private javax.swing.JCheckBox cboD1;
    private javax.swing.JCheckBox cboD2;
    private javax.swing.JCheckBox cboD3;
    private javax.swing.JCheckBox cbom1;
    private javax.swing.JCheckBox cbom2;
    private javax.swing.JCheckBox cbom3;
    private javax.swing.JCheckBox cbom4;
    private javax.swing.JPanel homePanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCalculate;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDesert;
    private javax.swing.JLabel lblMeat;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblTotalDesert;
    private javax.swing.JLabel lblTotalMeat;
    private javax.swing.JLabel lblTotalVegetables;
    private javax.swing.JLabel lblVegetables;
    private javax.swing.JPanel mainClassPanel;
    // End of variables declaration//GEN-END:variables
}
